# Generated by Django 2.0.4 on 2018-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='spoiler_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
