# Generated by Django 2.0.6 on 2018-06-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0005_auto_20180610_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_envelope_public_key',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
