# Generated by Django 2.0.6 on 2018-07-19 13:00

from django.db import migrations, models
import trilby_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0007_auto_20180718_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_avatar',
            field=models.ImageField(blank=True, default=None, upload_to=trilby_api.models.avatar_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='_header',
            field=models.ImageField(blank=True, default=None, upload_to=trilby_api.models.header_upload_to),
        ),
    ]
