# Generated by Django 2.0.6 on 2018-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0008_auto_20180719_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='magic_envelope_public_key',
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
