# Generated by Django 2.0.6 on 2018-07-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0010_auto_20180727_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='may_access',
        ),
    ]
