# Generated by Django 2.1 on 2018-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '__first__'),
        ('trilby_api', '0013_auto_20180828_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Actor'),
        ),
    ]
