# Generated by Django 2.1 on 2018-08-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0005_requestingaccess'),
        ('trilby_api', '0013_auto_20180828_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_requests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Actor'),
        ),
    ]
