# Generated by Django 2.1 on 2018-08-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0014_auto_20180828_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actor',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Actor'),
            preserve_default=False,
        ),
    ]
