# Generated by Django 2.1 on 2018-08-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0015_auto_20180828_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_requests',
        ),
    ]
