# Generated by Django 2.0.4 on 2018-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0005_auto_20180425_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_locked',
            new_name='locked',
        ),
    ]
