# Generated by Django 2.0.4 on 2018-05-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0007_auto_20180507_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='sensitive',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='status',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'unlisted'), (2, 'public'), (3, 'direct')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_visibility',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'unlisted'), (2, 'public'), (3, 'direct')], default=2),
        ),
    ]
