# Generated by Django 2.0.4 on 2018-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0008_auto_20180508_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(choices=[('F', 'is following'), ('B', 'has blocked'), ('M', 'has muted'), ('N', 'has muted notifications'), ('R', 'has requested access to')], max_length=1)),
            ],
        ),
    ]
