# Generated by Django 2.0.4 on 2018-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0009_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='visibility',
            field=models.CharField(choices=[('X', 'private'), ('U', 'unlisted'), ('P', 'public'), ('D', 'direct')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_visibility',
            field=models.CharField(choices=[('X', 'private'), ('U', 'unlisted'), ('P', 'public'), ('D', 'direct')], default='P', max_length=1),
        ),
    ]
