# Generated by Django 2.0.4 on 2018-05-10 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0010_auto_20180510_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='them',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='passive', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
