# Generated by Django 2.0.4 on 2018-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant', '0011_auto_20180510_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='what',
            field=models.CharField(choices=[('F', 'is following'), ('B', 'is blocked by'), ('R', 'has requested access to')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('us', 'them')},
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['us', 'them'], name='elephant_re_us_id_aa6dff_idx'),
        ),
    ]
